### ISSUE TITLE
Uninstaller

### ISSUE THREAD

**Issue by Cam** [MacMiniVault/Mac-Scripts#20]
Hi. What uninstaller fo I need to use to remove everything set up by this script? I ended up with a bunch of errors like the PID error and mysql generally not starting at all after running it :(

**Comment by jonschwenn** [comment]
There is no uninstaller.  MySQL does not provide one.  There are online tutorials that reference what to remove, but we will not script anything that uninstalls or potentially removes data.

**Comment by Cam** [comment]
What about some documentation on which versions/paths were used for the installation? Different installers use different paths, so it's a bit messy right now trying to clean up after this thing. Any useful info would be much appreciated.

**Comment by jonschwenn** [comment]
The installer is from MySQL and we leave it to install on it's default path.  It's installed into /usr/local/mysql and mysql is actually a symbolic link to something like /usr/local/mysql-5.6.25.......

**Comment by Cam** [comment]
Thanks @jonschwenn

For future reference, here is a handy little rundown of the steps for completely removing (some people may need further steps) mysql on OSx https://gist.github.com/Cam/a049c618b701ddea7f5e
