### ISSUE TITLE
Socket errors on new installation

### ISSUE THREAD

**Issue by Cam** [MacMiniVault/Mac-Scripts#21]
I am getting the following socket area with a clean install.
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
```
On selecting 'yes' when asked "DO YOU WANT TO LOAD MySQL ON BOOT? [Y/n]" the following information is provided...
```
/Library/LaunchDaemons/com.mysql.server.plist: Operation already in progress
/usr/local/mysql/support-files/mysql.server: line 362: pidof: command not found
/dev/fd/63: line 146: SORRY, MySQL IS NOT RUNNING ... THERE MUST BE A PROBLEM: command not found
```

**Comment by jonschwenn** [comment]
Clean install as in - a clean OS?  Or is this the machine you tried to uninstall on?

If parts of MySQL are still running or are around, and it confuses the MySQL installer, it'll start to error out.  We simply can't guarantee this script will work if MySQL has ever been installed on the system prior.

**Comment by Cam** [comment]
Hi @jonschwenn. It was a clean OS install, which I have since tried to uninstall the components created with this from as it didn't work. I think MySQL is just really messed up on Yosemite. I am sure I will find a workable solution at some point. Thanks for your help.
