### ISSUE TITLE
mmvwordpress/mmvwordpress - Update for Yosemite 10.10?

### ISSUE THREAD

**Issue by TheLensLord** [MacMiniVault/Mac-Scripts#22]
Is there an update for Yosemite 10.10? The script aborts when it checks for the system.

**Comment by jonschwenn** [comment]
For what it's worth - I plan on updating it to work with Yosemite. I had wanted to add new features to it to make things like permissions easier to deal with. Those features have been pesky to implement. That's the only reason why I have not yet pushed up an update.

**Comment by TheLensLord** [comment]
What can I do to help you? Probably not much, but I will do what I can.

**Comment by ajleach** [comment]
TheLensLord - the script was recently updated to support Yosemite installs. Thanks for the report.
