### ISSUE TITLE
pidof command not found

### ISSUE THREAD

**Issue by navels** [MacMiniVault/Mac-Scripts#23]
Your install script puts pidof into /usr/local/bin, but /usr/local/mysql/support-files/mysql.server sets the PATH variable to "/sbin:/usr/sbin:/bin:/usr/bin:$basedir/bin" and so cannot find pidof.

ps thanks for the great tool!

**Comment by jonschwenn** [comment]
Thanks for the catch.  I think it may be best to leave pidof in a place included in the default system path.  I'm thinking of sym linking in the $basdir/bin dir.  Thoughts?

**Comment by jonschwenn** [comment]
linked it and committed the update
