### ISSUE TITLE
mmvmysql: 5.6.26 installs a second startup daemon

### ISSUE THREAD

**Issue by navels** [MacMiniVault/Mac-Scripts#27]
Running the latest installer results in two plist files in /Library/LaunchDaemons:

com.mysql.server.plist
com.oracle.oss.mysql.mysqld.plist

This results in two attempts to start mysql when booting up which causes some problems.

**Comment by ajleach** [comment]
navels,

Thanks for reporting this issue - we have corrected this within the script.

**Comment by navels** [comment]
Thanks!
