### ISSUE TITLE
mmvwordpress with 10.11 / Server 5

### ISSUE THREAD

**Issue by dreness** [MacMiniVault/Mac-Scripts#28]
This script works in 10.11 with Server 5 with a couple adjustments:

1) support 10.11 in the version check by adding something like

    if [[  $(sw_vers -productVersion | grep '10.11') ]]
      then
      OSX=yes
    fi

2) In Server 5, web services are moved behind a [reverse proxy](https://discussions.apple.com/thread/7231060). If the WordPress site is using SSL, you need the following config in wp-config.php, before the include of wp-settings.php:

    if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')
           $_SERVER['HTTPS']='on';

Without the above config, an SSL site will load but without any CSS, and the browser console will be complaining about not wanting to load CSS resources from insecure sites if the page was loaded using https (this is a [new WebKit behavior](https://twitter.com/ohunt/status/644261245059641344)). Also, wp-admin will not load at all, failing with a 'too many redirects' error. The above config solves both problems, and has no effect on a non-SSL site in my testing.

Cheers,
-dre

**Comment by dreness** [comment]
For context, here's an explanation of how Joomla can deal with Server 5's reverse proxy in much the same way:
https://github.com/joomla/joomla-cms/issues/7916#issue-107404242

**Comment by ajleach** [comment]
We've allowed installs on 10.11 now, although we don't have a good way to know whether or not the site will be used for SSL at this point.
