### ISSUE TITLE
MySQL dmg link it seems to be broken

### ISSUE THREAD

**Issue by vdhub** [MacMiniVault/Mac-Scripts#30]
It seems that when you run the script it crashes lately . 

yosemites-Mac:~ yosemite$ bash <(curl -Ls http://git.io/eUx7rg)
bash <(curl -Ls http://git.io/eUx7rg)
Downloading MySQL Installers ... may take a few moments
######################################################################## 100.0%
/dev/fd/63: line 55: cd: /Volumes/mysql-5.6.26-osx10.8-x86_64/: No such file or directory
...
...
Installing MySQL, administrator password required ...
Password:

so i`m guessing that either the cdn was changed or the version was removed from the cdn. 

Thanks.

**Comment by vdhub** [comment]
It seems that the current link downloads few Kb and it stops so i guess something on the cdn side

**Comment by jonschwenn** [comment]
Updated from 5.6.26 to 5.6.28. The script should work once again, however 5.7.x needs to be evaluated and tested.
