### ISSUE TITLE
could you guys share how do you setup the static ip?

### ISSUE THREAD

**Issue by tfarina** [MacMiniVault/Mac-Scripts#31]
It would be handy to see if you guys have an automated way to setup the static ip for the mac mini servers.

**Comment by ajleach** [comment]
sudo networksetup -setmanual Ethernet [ipaddress] [subnet] [router]

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/networksetup.8.html

**Comment by tfarina** [comment]
@ajleach Thank you!
