### ISSUE TITLE
Is there 10.11 support for MySQL script? Errors during installation

### ISSUE THREAD

**Issue by iAm-Eric** [MacMiniVault/Mac-Scripts#32]
Hi MMV crew!

I have experienced an array of issues installing MySQL using the bash script in a clean 10.11 El Capi install. I assume it has something to do with SIP (I believe it is called?).

I have edited this message, originally I wanted to find a solution, but with having so many problems with 10.11 and other utilities such as node, nam, gulp etc, I have decided to painstakingly move back to Yosemite by clean install.

Otherwise for future possibilities, what is the state with the MMV MySQL script and 10.11? I see many of the scripts claim they will not work in El Capi but I was unable to find such test about the MySQL installer.

FYI, the installer breaks for me right away at the download link, it always results in a 16kb MySQL.dmg file.

Thanks,
Eric

**Comment by iAm-Eric** [comment]
okay, since backtracking to Yosemite I get the same problem... my downloads folder gets populated with the following:

- mmv-start.sh
- MySQL-install.plist
- MySQL.dmg (16bytes, not kb as I said in previous post)

Did I miss something embarrassingly obvious?

here are my errors:
```
Erics-MBP:~ eric$ bash <(curl -Ls http://git.io/eUx7rg)

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:
Downloading MySQL Installers ... may take a few moments
######################################################################## 100.0%
/dev/fd/63: line 55: cd: /Volumes/mysql-5.6.28-osx10.8-x86_64/: No such file or directory
...
...
Installing MySQL, administrator password required ...
installer: Error the package path specified was invalid: 'mysql-5.6.28-osx10.8-x86_64.pkg'.
ln: /usr/local/mysql/bin/pidof: No such file or directory
...
...
mv: rename /Users/eric/Downloads/mmv-start.sh to /usr/local/mysql/support-files/: No such file or directory
chown: /usr/local/mysql/support-files/mmv-start.sh: No such file or directory
sudo: /usr/local/mysql/support-files/mysql.server: command not found
sudo: /usr/local/mysql/support-files/mysql.server: command not found
/dev/fd/63: line 144: SORRY, MySQL IS NOT RUNNING ... THERE MUST BE A PROBLEM: command not found
```

**Comment by jonschwenn** [comment]
Hi Eric,

The `5.2.28` version has been removed from MySQL's download site. The script has been updated to `5.6.30` now and it should work now.

--
Jon

**Comment by iAm-Eric** [comment]
Indeed it does!

Thanks, Jon!
