### ISSUE TITLE
Uninstalling MySQL server

### ISSUE THREAD

**Issue by archatas** [MacMiniVault/Mac-Scripts#38]
Hello! How could I uninstall the MySQL server that was installed using this script?

If there is no automated script, which are the files that need to be deleted or edited?

**Comment by vdhub** [comment]
Well i did my own script but i did not use it for a while, 

Just have a look on it and see if it works 

`#!/bin/bash

echo "Server uninstall script starting ..."

echo "Please make sure that you have a backup of your database before you continue."

echo "...."

while true; do
	read -p "Are you sure you want to uninstall the server ? [y/N]" cnf
	case $cnf in
	[Yy]* ) sudo /usr/local/mysql/support-files/mysql.server stop; echo "Stopping server ..."; sudo rm -rf /usr/local/mysql*; echo "removing files ..."; sudo rm -rf /Library/StartupItems/MySQLCOM; sudo rm -rf /Library/PreferencePanes/My*; sudo rm -rf ~/Library/PreferencePanes/My*; sudo rm -rf /Library/Receipts/mysql*; sudo rm -rf /Library/Receipts/MySQL*; sudo rm -rf /private/var/db/receipts/*mysql*; sudo rm -rf /var/mysql; echo "...."; sudo rm -rf /Library/LaunchDaemons/com.mysql.server.plist; sudo rm -rf /Library/LaunchDaemons/com.oracle.oss.mysql.mysqld.plist; sudo rm -rf /tmp/mysql.sock; echo 'Mysql was uninstalled successfully'; break ;;
	[Nn]* ) break;;
	* ) echo "Please answer yes or no.";;
	esac
done		
`

**Comment by archatas** [comment]
Thanks! I will try this and will inform you if it worked.

**Comment by archatas** [comment]
It looks like the script worked well. Thanks again!

Maybe it could be included in the repository for other users too.
